### ISSUE TITLE
Want to join efforts?

### ISSUE THREAD

**Issue by andreaferretti** [yglukhov/variant#1]
Do you know of my ADT and pattern matching [library](https://github.com/andreaferretti/patty)?

**Comment by yglukhov** [comment]
Hey, i've looked through your readme, and its nice. It seems more focused on matching, while my lib is mostly a variant type that accepts values of any type. Matching in my lib is just a convenience feature. I like the decomposing idea a lot, but thats not a big priority for me personally =). Joining efforts sounds great. What do you propose? ;)

**Comment by andreaferretti** [comment]
On a better look, I think I misunderstood your variant type. I had assumed it was about providing a different way to declare variants in Nim, much like patty does with the `variant` macro, but now that I look better it seems the aim is rather disjoint. Sorry for the confusion :-(

**Comment by yglukhov** [comment]
No worries at all ;)
