### ISSUE TITLE
Don't update from github to new version variant-0.2.11

### ISSUE THREAD

**Issue by alexisad** [yglukhov/variant#6]
i did:
nimble.exe install https://github.com/yglukhov/variant.git
or 
nimble.exe install variant
I tried to 'nimble.exe uninstall variant' before... or delete folder \.nimble\pkgs\variant-0.2.10 before 

It didn't & nothing help: nimble always installs variant-0.2.10 but should install new variant-0.2.11

It helped only this way:
git clone https://github.com/yglukhov/variant.git
nimble.exe install

**Comment by yglukhov** [comment]
Fixed by tagging new release
